### ISSUE TITLE
Support for Wav2Vec2 with LM

### ISSUE THREAD

**Issue by AsianZeus** [ccoreilly/wav2vec2-service#3]
will this script be able to efficiently convert hugging face wav2vec2 with LM to onnx?

**Comment by ccoreilly** [comment]
As far as I know, the LM part is executed after the inference of the wav2vec2 acoustic model (AM) so the same onnx script should work but you need to run LM decoding separately. Probably easier for many if they add support for onnx AM in the huggingface library.

**Comment by AsianZeus** [comment]
Okay i get it, Thanks.

**Comment by AsianZeus** [comment]
Okay, I get it! Thanks.
